" Plugins
so ~/.vim/plugins.vim

" Base settings
so ~/.vim/base.vim

" GUI settings
so ~/.vim/gui.vim

" FileType settings
so ~/.vim/ftype.vim

" Keybinds
so ~/.vim/keybinds.vim

" Functions, etc.
so ~/.vim/func.vim
