# brew completions
if [[ $(uname) == 'Darwin' ]]; then
  fpath=(/usr/local/share/zsh-completions $fpath)
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd nomatch notify
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

# The following lines were added by compinstall

zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-]=** r:|=** l:|=*'
zstyle ':completion:*' use-compctl false
zstyle :compinstall filename '/home/jrpko/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Paths
#
if [[ $(uname) == 'Darwin' ]]; then
  # ls colors
  export LSCOLORS=GxFxCxDxBxegedabagaced

  # set path to use brew utils (more up-to-date than OS X system utils)
  # can be done in /etc/paths if needed system-wide
  # check if path already begins with /usr/local/bin
  echo $PATH | grep -q -s "^${LOCALBIN}"
  # if not, update path
  if [[ $? -eq 1 ]]; then
    export PATH=$LOCALBIN:$PATH
  fi
fi

# Source files in ~/.zshrc.d
if [ -d "$HOME/.zshrc.d" ]; then
    for file in "$HOME/.zshrc.d"/*; do
        [ -f "$file" ] && source "$file"
    done
fi
