#For OSX
if [ `uname` == 'Darwin' ]
then
    #command line colors & ls colors
    export CLICOLOR=1
    export LSCOLORS=GxFxCxDxBxegedabagaced
    LSCOLORS="$LSCOLORS:di=38;5;208"
    #bash completion through brew. Hopefully this is installed!
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

# PS1 # TODO: fix this file to look cleaner this is gross

# LETS ADD COLOR (ty gemini)
export PS1="\[\033[1;92m\]\u\[\033[0m\]@\[\033[38;5;208m\]\h\[\033[0m\]:\w\$ "
# more readable dirs (blue disappears on a black background)
export LS_COLORS="$LS_COLORS:di=38;5;208"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Load Angular CLI autocompletion.
source <(ng completion script)
