#For OSX
if [ `uname` == 'Darwin' ]
then
    #command line colors & ls colors
    export CLICOLOR=1
    export LSCOLORS=GxFxCxDxBxegedabagaced
    #bash completion through brew. Hopefully this is installed!
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        . $(brew --prefix)/etc/bash_completion
    fi
fi

#Add aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
